#RewriteEngine on
#RewriteCond %{HTTP_HOST} ^jarredmack\.com$ [OR]
#RewriteCond %{HTTP_HOST} ^www\.jarredmack\.com$
#RewriteRule ^api\.jarredmack\.com$ "http\:\/\/api\.jarredmack\.com\/" [R=301,L]


Options +FollowSymlinks
RewriteEngine on
rewritecond %{http_host} ^jarredmack.com [nc]
rewriterule ^(.*)$ http://www.jarredmack.com/$1 [r=301,nc]



<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</IfModule>
